[package]
name = "token_bound_accounts"
version = "0.3.0"
edition = "2024_07"
authors = ["Horus Labs <horuslabsio@gmail.com>"]
description = "A port of ERC6551 to Starknet"
repository = "https://github.com/horuslabsio/TBA/blob/main/Scarb.toml"
license-file = "LICENSE"
keywords = ["ERC6551", "tokenbound", "cairo", "contracts", "starknet", "standards"]
readme = "README.md"
cairo_version = "2.8.2"
homepage = "https://www.tbaexplorer.com/"
documentation = "https://github.com/horuslabsio/TBA-SDK"


# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
casm = true

[lib]

[dependencies]
starknet = "2.8.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.17.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.30.0" }

[tool.snforge]
# exit_first = true
